### ISSUE TITLE
Significance of the yarn.lock

### ISSUE THREAD

**Issue by sjorsvanheuveln** [CloseBrace/MusicList#11]
Hi Chris, 

I'm sure you've mentioned it somewhere, but what is the significance of the yarn.lock file? Can I throw this away when I clone your repo? And how to use this file when using NPM?

**Comment by sjorsvanheuveln** [comment]
Nevermind. I hear you talk in video 004 on production builds, I'll just switch to Yarn.

**Comment by cwbuecheler** [comment]
It's useful but not super necessary for this particular situation. Basically it's just that Yarn doesn't actually read your package.json when you do an install, it reads the lockfile. It only goes to package.json if the lock file doesn't exist. This allows for much more rigid consistency between installations.

Note that new versions of NPM create a lock file, now, too. Honestly the latest versions of NPM make Yarn less significant. They've taken most of what made Yarn a desirable addition.

https://yarnpkg.com/lang/en/docs/yarn-lock/ for more info.
