### ISSUE TITLE
Clone last commit working, only HMR broken.

### ISSUE THREAD

**Issue by sjorsvanheuveln** [CloseBrace/MusicList#13]
Hi Chris,

I've managed to get a working clone of the master branch. However I came across an old problem. My HMR is broken now. When I change something and I save it, I get the following stuff in the console:
```
[Log] [HMR] bundle rebuilding (build.js, line 123156)
[Log] [HMR] bundle rebuilt in 576ms (build.js, line 123164)
[Log] [HMR] Checking for updates on the server... (build.js, line 123246)
[Log] [HMR] Updated modules: (build.js, line 123319)
[Log] [HMR]  - ./src/components/home/HomePage.jsx (build.js, line 123321)
[Log] [HMR]  - ./src/components/home/HomePageContainer.jsx (build.js, line 123321)
[Log] [HMR]  - ./src/components/Template.jsx (build.js, line 123321)
[Log] [HMR]  - ./src/components/TemplateContainer.jsx (build.js, line 123321)
[Log] [HMR] App is up to date. (build.js, line 123326)
```

So it appears to be working, however the changes are not updated in the browser. What could be the problem?

**Comment by cwbuecheler** [comment]
That's very odd. Is it possible that you ran a production build script which generated a static file with the same name?

**Comment by sjorsvanheuveln** [comment]
Could be! How can I check this or avoid this?

**Comment by cwbuecheler** [comment]
The way I avoid it is by having the production build produce a differently-named file, and then doing an `if` in `/views/index.ejs` like this:

```
  <% if (process.env.NODE_ENV === 'production') { %>
      <script src="/javascripts/build-prod.js"></script>
  <% } else { %>
    <script src="/javascripts/build.js"></script>
  <% } %>
```

If you're already doing that, though, then it's probably not the problem.

**Comment by cwbuecheler** [comment]
Oh, and you can check by seeing if there's a `build.js` in `/public/javascripts`

**Comment by sjorsvanheuveln** [comment]
Allright, no this is not the issue. I cloned your repo, and could only find the build files in there.

**Comment by cwbuecheler** [comment]
Oh, hmm, I misunderstood the issue -- it's actually possible that the hot-reloading is broken in this repo. It's crazy fragile. I may have just not noticed because I hard-refresh so much anyway. I'll look into it.

**Comment by sjorsvanheuveln** [comment]
Yeah, I know, that's why I kept it working on my other project at the expense of the production build reconfiguration. But would be awesome if your final version had the hot-reloading still working! Thanks in advance.

**Comment by sjorsvanheuveln** [comment]
Hi Chris,

I think I managed to find a way. I don't know if it is the proper thing to do, but I got it working again with only an adjustment in index.js. I changed this:
```
if (module && module.hot) {
  module.hot.accept('./components/TemplateContainer', () => {
    renderApp(TemplateContainer);
  });
}
```

Into this:
```
if (module && module.hot) {
  module.hot.accept('./components/TemplateContainer', () => {
    const NextApp = require('./components/TemplateContainer').default;
    renderApp(NextApp);
  });
}
```

Found the solution here:
https://github.com/webpack/webpack-dev-server/issues/100#issuecomment-271146394

**Comment by cwbuecheler** [comment]
Nice. I have no idea if that's "proper" either but a) it works and b) it's for the development server only so it's not like it needs to be perfect. :)

I'll make a change to the repo and probably update the relevant tutorials, too (though not the videos).

**Comment by sjorsvanheuveln** [comment]
Yeah, it should only be functional for the moment and it would be a pain to hard refresh to see all the changes I make. This is gonna save a headache!

**Comment by mraguso2** [comment]
Man I wish I found this link 28 mins ago - I actually found "_referenced issue in MusicList_" in that webpack-dev-server solution link literally right before I was about to try it, thank you! @sjorsvanheuveln ..Helped confirm! and it works for me too!
