### ISSUE TITLE
compileFormData in RegisterPage.jsx?

### ISSUE THREAD

**Issue by sjorsvanheuveln** [CloseBrace/MusicList#4]
Is it me or is there a undefined compileFormData in: /src/components/account/RegisterPage.jsx
Where is it defined?

**Comment by cwbuecheler** [comment]
Whoops. Yeah, that should be "handleValidSubmit" now ... although I did a bit of testing and it looks like our form module is enter-key-aware anyway, so we can probably just remove that and simplify the code. I'll do a "fixes and cleanup" tutorial soon. Until then, I'll leave this open.

**Comment by cwbuecheler** [comment]
Fixed locally. Will be fixed publically in tutorial 77.

**Comment by sjorsvanheuveln** [comment]
The same "bug" is also in loginpage.jsx.

**Comment by cwbuecheler** [comment]
Just fyi, this bug has been caught and fixed in all files in the new updates that are coming to the series, probably this afternoon (if not, definitely tomorrow).
