### ISSUE TITLE
Cannot use bootstrap add Lesson 34

### ISSUE THREAD

**Issue by nguyentienviet123456** [CloseBrace/MusicList#5]
i do follow your tutorial, but bootstrap cannot using

**Comment by nguyentienviet123456** [comment]
sorry for my bad english, and i config webpack file folow your step and import as your code, but cannot apply bootrap css into my view. I have to create a bootstrap.css file in folder stylesheets to apply bootstrap.

**Comment by cwbuecheler** [comment]
No problem about the english. It's fine. I understand what you're saying but I am not sure why it wouldn't be working. Is your code in github? I'd like to look at it and see if I can see what's breaking.

**Comment by nguyentienviet123456** [comment]
https://github.com/nguyentienviet123456/musiclist
this is my repo, can you check it for me ?

**Comment by cwbuecheler** [comment]
Open `/src/index.jsx`

Change line 5 from:
```
import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
```
to
```
import 'bootstrap/dist/css/bootstrap.min.css';
```
then DELETE `/public/stylesheets/style.css` entirely.

restart your server, and you should be able to use bootstrap.

**Comment by nguyentienviet123456** [comment]
okey it's work, thank you so much, cwbuecheler !

**Comment by cwbuecheler** [comment]
Glad I could help! Good luck with the rest of the tutorials.
