### ISSUE TITLE
cannot logout API

### ISSUE THREAD

**Issue by nguyentienviet123456** [CloseBrace/MusicList#8]
i do this api but it's dont have req.user object
this is my code : https://github.com/nguyentienviet123456/musiclist

**Comment by cwbuecheler** [comment]
two problems with your code:

1. You're missing the ExpressSession config / use in app.js. you need this up in your require blocks at the top:

```
const expressSession = require('express-session')({
  secret: 'random strings here are good',
  resave: false,
  saveUninitialized: false,
});
```

and this in the "use" block starting around line 44:

```
app.use(expressSession);
```

Also, your logout route is miscoded. It's trying to send a username after the logout, which obviously can't happen. Please make sure your code matches what's in the tutorial. It should be this:

```
router.get('/logout', (req, res) => {
  console.log(req.user);
  req.logout();
  console.log(req.user);
  return res.send(JSON.stringify(req.user));
});
```

**Comment by nguyentienviet123456** [comment]
thank you so much !

**Comment by nguyentienviet123456** [comment]
done !
